### ISSUE TITLE
Issue with CSS w.r.t `no continue to edit` button 

### ISSUE THREAD

**Issue by S2606** [TrangPham/django-admin-confirm#25]
![Screenshot 2021-03-31 at 11 52 07 AM](https://user-images.githubusercontent.com/18497513/113099408-88165480-9217-11eb-9532-273f0e12c7ba.png)

django_admin_confirm version number 0.2.3, python 3.7, django 2.2.5.

**Comment by TrangPham** [comment]
Hey @S2606 I saw you closed the issue. Was there something wrong with the CSS?
