### ISSUE TITLE
Redis Error: wrong number of arguments for 'del' command

### ISSUE THREAD

**Issue by chrismaille** [TrangPham/django-admin-confirm#46]
**Describe the bug**
`redis` returning `wrong number of arguments for 'del' command` when called from `django-admin-confirm` and cache backend is configured to Redis. Works without issues when backend is Memcached.

**To Reproduce**
1. Install latest redis version `pip install redis`
2. Configure Django settings cache backend to Redis
3. Open a model configured for confirmation
4. Confirm Save

**Expected behavior**
The instance model needs to be updated.

**Screenshots**
![image](https://user-images.githubusercontent.com/11915032/217955414-f11f270b-7f76-448f-8537-4408ad9c01e5.png)

**Versions:**
 - django==4.1.6
 - redis==4.5.1
 - django-admin-confirm==1.0.0

**Additional context**
![image](https://user-images.githubusercontent.com/11915032/217954925-bb80ac8c-5bad-46e4-a66e-6bc16903fbd9.png)

**Comment by NeilujD** [comment]
A fix has been made in the coming Django 4.2: https://github.com/django/django/commit/608ab043f75f1f9c094de57d2fd678f522bb8243
But it would be great to have a workaround in the meantime !

**Comment by TrangPham** [comment]
Thanks for the detailed bug report @chrismaille.
And thanks @NeilujD for linking to the resolution. 
I've made a change to fix this issue within our code base. I'll make a new minor release soon
